mautic_auth:
  host: https://mautic.example.org
  username: foo
  password: bar

keycloak_auth:
  server_url: https://sso.example.org/auth/
  realm_name: foo
  client_id: mautic-import
  client_secret_key: 12345-121212-1212

mautic:
  transfer_constraint: segment:keycloak-export
  default_roles:
    - uma_authorization
    - offline_access

  boolean_role_fields:
    activist: ismember
    guest: guest

  role_fields:
    - arbeitsgruppen
    - interessensgruppen
    - gremium
    - bezirksgruppe
    - specialroles

email:
  src: it@example.org
  dests:
    - it@example.org
  host: smtp.example.org
  user: foo
  password: 'bar'
